apiVersion: apps/v1
kind: Deployment
metadata:
  name: depdemo-api
  namespace: depdemo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: depdemo-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 # one extra pod allowed during rollout
      maxUnavailable: 0 # never take a pod down before a new one is ready
  template:
    metadata:
      labels:
        app: depdemo-api
    spec:
      containers:
        - name: api
          image: localhost/depdemo-api:v2
          lifecycle:
            preStop:
              exec:
                command: ["sleep", "5"]
          readinessProbe:
            httpGet:
              path: /
              port: 3031
            initialDelaySeconds: 3
            periodSeconds: 2
          env:
            - name: MONGO_HOST
              value: mongodb
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_DB
              value: depdemo-db
            - name: MONGO_USER
              value: admin
            - name: MONGO_PASSWORD
              value: password
            - name: PORT
              value: "3031"
